- name: Semperti test
  hosts: all
  gather_facts: true
  tasks:
    - name: 1. Install Apache Packages
      yum: name={{ item }} state=present
      with_items:
          - java-1.8.0-openjdk
          - maven
      become: yes
      become_user: jsfrnc
      cbecome_flags: '-s /bin/sh' 
 
    - name: Install MySQL 5.7 repo
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

   # - name: Use 'argv' to send a command as a list - leave 'command' empty
   #   command: 'sudo wget https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm'
   #   become: yes
   #   become_user: jsfrnc
